### ISSUE TITLE
Next steps

### ISSUE THREAD

**Issue by ggwpp** [freifunkMUC/wg-access-server-chart#4]
The latest version I checked from https://freie-netze.org/wg-access-server is v0.6.0. But in this repo it is `0.9.5`.
Could you help package and push chart to your helm repo registry ?

**Comment by GoliathLabs** [comment]
Hi @ggwpp, as mentioned in https://github.com/freifunkMUC/wg-access-server/issues/97 we don't have the expertise or time to maintain these charts ourselves. Since the wg-access-server helm repository was just a legacy and has not been previously removed, it has been done with https://github.com/freifunkMUC/wg-access-server/pull/237. If we have a person who can take care of the charts and associated maintenance, we can publish these charts again on a regular basis.

**Comment by ggwpp** [comment]
Hi @GoliathLabs , Im happy to help. I have experience on k8s and helm-chart.
What do you think how I should get started ?

**Comment by GoliathLabs** [comment]
It would be nice if you could coordinate with @iMartyn @DerRockWolf @elcomtik & @zandemax and those who want to contribute to maintaining the chart. As mentioned in the other issues, @DasSkelett and I don't really have much experience with Helm Charts or Kubernetes yet.

**Comment by catrielmuller** [comment]
I created a PR to do the Deployment and fix the documentation.
in a meantime you can use my repo if you needed.

```bash
$ helm install wireguard --repo https://catrielmuller.github.io/wg-access-server-chart/ wg-access-server
```

**Comment by GoliathLabs** [comment]
@catrielmuller your PR is now merged and the workflow seems to be working fine. Thanks again! 😄
